#!/usr/bin/env bash
# Compile every .lean file under projects/ via `lake env lean` and capture
# pass/fail + first diagnostic. Generates STATUS.md per project subdir plus
# a top-level SUMMARY.md.

set -u
cd "$(dirname "$0")/.." || exit 2
TIMEOUT="${OCTIVE_TIMEOUT:-30}"

echo "[check-all] building OctiveLean once…"
lake build >/dev/null 2>&1 || { echo "lake build failed" >&2; exit 1; }

declare -A counts=([ok]=0 [error]=0 [timeout]=0)

first_diag() {
  # First line containing 'error' (Lean diagnostic format), trimmed.
  grep -m1 -E '^[^:]+\.lean:[0-9]+:[0-9]+:[[:space:]]*error' "$1" 2>/dev/null \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
    | head -c 140
}

for dir in projects/*/; do
  proj="${dir%/}"
  proj_name="$(basename "$proj")"
  status_md="$proj/STATUS.md"
  {
    echo "# $proj_name (Lean DSL)"
    echo
    echo "_Generated by \`projects/check-all.sh\`._"
    echo
    echo "Source: \`~/.env/octive/$proj_name/\` (transpiled by \`projects/transpile.py\`)"
    echo
    echo "| Lean file | Compiles? | First diagnostic |"
    echo "| --- | --- | --- |"
  } > "$status_md"

  shopt -s nullglob
  for f in "$proj"/*.lean; do
    name="$(basename "$f")"
    out="$f.check"
    timeout --foreground "$TIMEOUT" lake env lean "$f" >"$out" 2>&1
    rc=$?
    if (( rc == 124 )); then
      status="timeout"
      diag="exceeded ${TIMEOUT}s"
    elif (( rc == 0 )); then
      status="ok"
      diag=""
    else
      status="error"
      diag="$(first_diag "$out")"
    fi
    counts[$status]=$((counts[$status]+1))
    diag_escaped="${diag//|/\\|}"
    echo "| \`$name\` | $status | $diag_escaped |" >> "$status_md"
  done
  shopt -u nullglob
done

{
  echo "# Projects summary (Lean DSL)"
  echo
  echo "Generated $(date '+%Y-%m-%d %H:%M:%S')."
  echo
  echo "| Outcome | Count |"
  echo "| --- | --- |"
  for k in ok error timeout; do
    echo "| $k | ${counts[$k]} |"
  done
  echo
  echo "Per-project tables: see each \`projects/<name>/STATUS.md\`."
} > projects/SUMMARY.md

echo
echo "[check-all] done."
echo "  ok=${counts[ok]} error=${counts[error]} timeout=${counts[timeout]}"
echo "  summary -> projects/SUMMARY.md"
